### ISSUE TITLE
Is The Noise Rate Known in Label Noise Modelling? 

### ISSUE THREAD

**Issue by XinshaoAmosWang** [PaulAlbert31/LabelNoiseCorrection#2]
Hi, 

I would like to know whether the noise rate is given in Label Noise Modelling? 
If the noise rate is not given, how do you compute p(k), i.e., p(0) for clean set and p(1) for noisy set?

According to my current understanding, the noise rate has to be given so that p(1) = noise rate in the estimation stage of modelling. Is my understanding right?

Thanks.

**Comment by EricArazo** [comment]
Hello,

The label noise modeling is unsupervised, i.e the noise rate is not needed. The estimation stage only requires the loss values and the parameters from the beta distributions (Eq. 6 and 7 in the paper). Regarding the first part of your question, we do not compute p(k), the mixture model gives us the posterior probabilities, p(k|l), that are used to determine if one sample is clean or noisy.

**Comment by XinshaoAmosWang** [comment]
Hi @EricArazo , 
Thanks for your kind reply. 

Yeah, my question is that how do you compute posterior probability p(k|l) without knowing the prior p(k).

**Comment by EricArazo** [comment]
You are welcome @XinshaoAmosWang , and thank you for your interest in our work. 

The prior p(k) corresponds to the lambda_k (Eq. 8 in the paper) estimated through the EM process. In other words, we are estimating the p(k) to compute the p(k|l) as commonly done in mixture models.

Please let us know if you have further doubts.
