### ISSUE TITLE
 bmm_model AttributeError: 'int' object has no attribute 'look_lookup'

### ISSUE THREAD

**Issue by uRENu** [PaulAlbert31/LabelNoiseCorrection#6]
error in train.py:

when using the function: train_mixUp_HardBootBeta, the input parameter bmm_model is 0
<img width="964" alt="截屏2021-11-10 下午1 38 27" src="https://user-images.githubusercontent.com/54517380/141056303-de28bef1-4afc-4152-9d10-467e304c5639.png">

then error encountered :
bmm_model AttributeError: 'int' object has no attribute 'look_lookup'

**Comment by uRENu** [comment]
"the input parameter bmm_model is 0"   see line 125 in train.py

should function track_training_loss(line 184 in train.py) be executed before function train_mixUp_HardBootBeta(line 159 in train.py)?

**Comment by EricArazo** [comment]
Hello uRENu,  thank you for your interest in our code and apologies for the late reply. You are correct, the function track_training_loss should be called before train_mixUp_HardBootBeta to create the bmm_model. This is why the function train_mixUp_HardBootBeta is called only if epoch > bootstrap_ep_mixup. In almost all the setups we have a warm-up stage where the model trains without bootstrapping to obtain better features and perform a better noise detection. Please, feel free to ask any other questions.
